### ISSUE TITLE
Can't access Jset in python version

### ISSUE THREAD

**Issue by fsxbhyy** [tensor4all/xfac#11]
Dear developer,
My current task requires me to unbox the Tensor Train object, and calculate the TCI in a pytorch tensor form. For this reason, I want to extract all multi-index generated by the TCI. However, when I try to access Jset, it shows the following:

 TypeError: Unable to convert function return value to a Python type! The signature was
	(self: xfacpy.TensorCI2) -> list[xfac::IndexSet<std::__cxx11::basic_string<char32_t, std::char_traits<char32_t>, std::allocator<char32_t> > >]

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.

Could you please let me know how to fix this? Looks like some problem with the compiling process for python library.
Thanks for your help!

Tao Wang

**Comment by yurielnf** [comment]
Thanks for your feedback @fsxbhyy ! 
I think the problem is solved, see [here](https://github.com/tensor4all/xfac/blob/main/notebook/example_integral.ipynb)

**Comment by fsxbhyy** [comment]
Thanks for you prompt response!



Yuriel ***@***.***> 于2024年9月13日周五 10:30写道：
