### ISSUE TITLE
get_TP1_at and get_P1T_at not exported to python

### ISSUE THREAD

**Issue by fsxbhyy** [tensor4all/xfac#13]
Dear Developer,

I encountered stability issue when I perform inverse explicitly on the pivot matrix that I recalculated given Iset and Jset. Based on my understanding, it is best to use the LU form to calculate everything instead. I think the get_TP1_at and get_P1T_at functions does this implicitly. However, it seems these two functions are not exported to python for CTensor2. Could you please let me know how to access these two functions? 
I also didn't understand what CTensor2.P currently saves. Based on documentation, it is not the original pivot matrix, but the LU form.

Thanks for your help!

Tao Wang

**Comment by yurielnf** [comment]
Dear Tao,
I have exported these two methods to python.
Thanks for your interest!
